#ifndef DX9MT_OBJECT_IDS_H
#define DX9MT_OBJECT_IDS_H

#include <stdint.h>

typedef uint32_t dx9mt_object_id;

enum dx9mt_object_kind {
  DX9MT_OBJECT_KIND_INVALID = 0,
  DX9MT_OBJECT_KIND_DEVICE = 1,
  DX9MT_OBJECT_KIND_SWAPCHAIN = 2,
  DX9MT_OBJECT_KIND_BUFFER = 3,
  DX9MT_OBJECT_KIND_TEXTURE = 4,
  DX9MT_OBJECT_KIND_SURFACE = 5,
  DX9MT_OBJECT_KIND_VERTEX_SHADER = 6,
  DX9MT_OBJECT_KIND_PIXEL_SHADER = 7,
  DX9MT_OBJECT_KIND_STATE_BLOCK = 8,
  DX9MT_OBJECT_KIND_QUERY = 9,
  DX9MT_OBJECT_KIND_VERTEX_DECL = 10,
};

#endif
